export const ACTION_TYPES = {
    CREATING_NEW_SCHOOL_ACTION_TYPE: 'CREATING_NEW_SCHOOL',
    SCHOOL_DATA_UPDATING_ACTION_TYPE: 'SCHOOL_DATA_UPDATING',
    REGISTRATION_NEW_COURSE_ACTION_TYPE: 'REGISTRATION_NEW_COURSE',
    LEARNING_GROUP_START_ACTION_TYPE: 'LEARNING_GROUP_START',
    LESSON_DONE_ACTION_TYPE: 'LESSON_DONE',
    LEARNING_GROUP_END_ACTION_TYPE: 'LEARNING_GROUP_END',
    CHOOSE_SCHOOLE_ACTION_TYPE: 'CHOOSE_SCHOOL',
    CHOOSE_COURSE_ACTION_TYPE: 'CHOOSE_COURSE'

}